framework:
    messenger:
        transports:
            sync: 'sync://'
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus: ~
        routing:
            'TegCorp\SharedKernelBundle\Application\Command\CommandInterface': sync
            'TegCorp\SharedKernelBundle\Application\Query': sync
