framework:
    messenger:
        transports:
            sync: 'sync://'
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus: ~
        routing:
            'App\Shared\Application\Command\CommandInterface': sync
            'App\Shared\Application\Query\QueryInterface': sync
