services:
  php:
    build: ./docker/php
    restart: on-failure
    volumes:
      - .:/home/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true

volumes:
  caddy_data:
  caddy_config: