parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    TegCorp\SharedKernelBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
