parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    TegCorp\SharedKernelBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    TegCorp\SharedKernelBundle\Application\Command\AsCommandHandler:
        tags:
            - { name: messenger.message_handler, bus: command.bus }
